######################################################################
# Automatically generated by qmake (3.0) Tue May 28 10:31:34 2019
######################################################################

QT += widgets testlib
TEMPLATE = app
TARGET = testqstring
INCLUDEPATH += .

CONFIG += console debug c++11
CONFIG -= app_bundle

# Input
HEADERS += testqstring.h
SOURCES += testqstring.cpp
