######################################################################
# Automatically generated by qmake (3.0) Mon May 27 13:39:20 2019
######################################################################

TEMPLATE = app
TARGET = language
INCLUDEPATH += .

DESTDIR=bin/.
OBJECTS_DIR=obj/.
MOC_DIR=moc/.

# Input
SOURCES += main.cpp lineprocessor.cpp jsondata.cpp

CONFIG += console

DEFINES +=QT_DEPRECATED_WARNINGS
