######################################################################
# Automatically generated by qmake (3.0) Thu May 30 09:53:41 2019
######################################################################

QT += testlib
QT += core
QT -= gui
TEMPLATE = app
TARGET = testobjectlist
INCLUDEPATH += . ../ ../../

CONFIG += debug console

# Input
SOURCES += testobjectlist.cpp ../../objectlist.cpp ../log.cpp
