######################################################################
# Automatically generated by qmake (3.0) Wed May 29 11:15:46 2019
######################################################################

QT += testlib
QT -= gui

TEMPLATE = app
TARGET = ../testJsonData
INCLUDEPATH += . ../..

# Input
SOURCES += testjsondata.cpp ../../jsondata.cpp
