######################################################################
# Automatically generated by qmake (3.0) Wed May 29 11:15:46 2019
######################################################################

QT += testlib core
QT -= gui

TEMPLATE = app
TARGET = testjsondata
INCLUDEPATH += ./ ../ ../..

CONFIG += debug console

# Input
SOURCES += testjsondata.cpp ../../jsondata.cpp ../../objectlist.cpp ../log.cpp
